#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php';

$init = new \app\AppInit();
$init->start();

var_dump($init->newDB()->doc());

$helperSet = new \Symfony\Component\Console\Helper\HelperSet(array(
    'dm' => new \Doctrine\ODM\MongoDB\Tools\Console\Helper\DocumentManagerHelper($init->newDB()->doc()),
    'init' => new \Meister\Meister\Console\Helper\MeisterHelper($init)
));

$app = new \Symfony\Component\Console\Application('Console - Meister');
$app->setHelperSet($helperSet);
$app->addCommands(array(
    new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateDocumentsCommand(),
    new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateHydratorsCommand(),
    new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateProxiesCommand(),
    new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateRepositoriesCommand(),
    new \Doctrine\ODM\MongoDB\Tools\Console\Command\QueryCommand(),
    new \Doctrine\ODM\MongoDB\Tools\Console\Command\ClearCache\MetadataCommand(),
    new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\CreateCommand(),
    new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\DropCommand(),
    new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\UpdateCommand(),
));

$app->addCommands(array(
    new \Meister\Meister\Console\hello(),
    new \Meister\Meister\Console\privatekey(),
    new \Meister\Meister\Console\backup(),
	new \Meister\Meister\Console\twig_compile(),
	new \Meister\Meister\Console\translate()
));

$app->run();