twig:
  cache: false
  debug: true

database:
  type: mongo
  name: MONGODB
  host: 127.0.0.1
  port:
  user:
  pass:

cache:
  type: redis
  host: 127.0.0.1

session:
  time: 60

auth:
  field: email
  entity: src\teste\Document\Users

mail:
  stmp: true
  host:
  port:
  user:
  pass:
  from:

field_user: email

modules:
 - teste
#
# Se for true, por padrão vai verificar se ele está authenticado para poder acessar o controller,
# e para poder acessar o controller sem autenticação precisa setar o annotation @notauthenticated
#
# Se for false, por padrão ele vai deixar acessar todos os controllers
# e so vai verficar se está logado se tiver setado no annotation @authenticated
#
authentication: true